sudo: required
dist: trusty
language: node_js
node_js:
  - '5'
  - '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
    code_climate:
      repo_token: <>
services:
  - mongodb
after_success:
  - npm run coverage
  - coveralls
notifications:
  email: false
  slack:
    rooms:
      - csci-450-odd:bRieDpCz5eHZvruypGO182AX#build-travisci
